<?php

// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB

$databaseDialect = "mysql";

$databaseHostname = "localhost";

$databasePort = 3306;

$databaseName = "esgi";

$databaseUsername = "root";

$databasePassword = "root";
